### ISSUE TITLE
Ant path matcher

### ISSUE THREAD

**Issue by kfirfer** [elibracha/openapi-diff-ignore#4]
Hi

proposal : the path matching mabye can be implement as an Ant path matcher
perhaps this library from spring can help:
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html

**Comment by elibracha** [comment]
great proposal will look in to it.

**Comment by elibracha** [comment]
added AntPathMatcher instead of custom function. resolved.
